import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
// This path is correct as long as Registry.tsx is in the same `app` folder.
import StyledComponentsRegistry from "./Registry"; 
import { QueryProvider } from "@/providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-space-grotesk',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceGrotesk.variable}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* This is the correct implementation */}
        <StyledComponentsRegistry>
          <QueryProvider>
            {children}
          </QueryProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}